#!/usr/bin/python

def hd(kvantil, niz):
    i = int(kvantil * len(niz))
    return niz[i]
                        
ulaz = open('zad2data.txt', 'r').read().split('\n')
nizovi  = {}

n = 0
for linija in ulaz:
    brojevi = linija.split(' ')
    brojevi = [float(P) for P in brojevi]
    brojevi.sort()
    
    n += 1
    nizovi[n] = brojevi
              
print "Hyp # Q10 # Q20 # Q30 # Q40 # Q50 # Q60 # Q70 # Q80 # Q90"	
for key in nizovi.keys():
    hdr = str(key)
    for q in range(1,10):
        hdr += " # " + str(hd(float(q)/10, nizovi[key]))
    print hdr
  